config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: 'home#positive_feedbacks'
  get 'home/positive_feedbacks' => 'home#positive_feedbacks'
  get 'home/negative_feedbacks' => 'home#negative_feedbacks'
  get 'home/topics' => 'home#topics'
  get 'home/topic_details' => 'home#topic_details'
  get 'home/charts' => 'home#charts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed_back.rb
class FeedBack < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def positive_feedbacks
    res = RestClient.get "#{Constants::BaseUrl}/positive_feedbacks"
    res = JSON.parse(res.body) rescue {}
    @feed_backs = res['result']
  end

  def negative_feedbacks
    res = RestClient.get "#{Constants::BaseUrl}/negative_feedbacks"
    res = JSON.parse(res.body) rescue {}
    @feed_backs = res['result']
  end

  def topics
    res = RestClient.get "#{Constants::BaseUrl}/topics"
    res = JSON.parse(res.body) rescue {}
    @topics = res['result']
  end

  def topic_details
    word = params[:word]
    res = RestClient.get "#{Constants::BaseUrl}/topic_details?word=#{word}"
    res = JSON.parse(res.body) rescue {}
    @feed_backs = res['result']
  end

  def charts
    res = RestClient.get "#{Constants::BaseUrl}/charts"
    res = JSON.parse(res.body)['result'] rescue {}
    @bar_chart_data = [res['bar_chart_hash']['positive'], res['bar_chart_hash']['negative'], res['bar_chart_hash']['neutral']]

    i = 0
    @pie_chart_x = []
    @pie_chart_y = []
    @word_count_chart_data = res['pie_chart_hash']
    @word_count_chart_data.each do |k, v|
      @pie_chart_x << k
      @pie_chart_y << v
      i += 1
      break if i > 10
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/charts.html.erb
<div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content">
        <!-- Begin Page Content -->
        <div class="container-fluid">
            <div class="row">
              <div class='col-md-12'>
                <canvas id="barchart" style="width:100%;max-width:800px"></canvas>
              </div>
              <div class='col-md-12'>
                <canvas id="piechart" style="width:100%;max-width:800px"></canvas>
              </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </div>
</div>

<!-- Page level plugins -->
<script src="/vendor/chart.js/Chart.min.js"></script>
<!-- Page level custom scripts -->
<!-- <script src="/js/demo/chart-area-demo.js"></script>
<script src="/js/demo/chart-pie-demo.js"></script> -->

<script>
var xValues = ["Positive", "Negative", "Neutral"];
var yValues = <%= raw @bar_chart_data %>;
var barColors = ["green", "red", "lightblue"];

new Chart("barchart", {
  type: "bar",
  data: {
    labels: xValues,
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    legend: {display: false},
    title: {
      display: true,
      text: "Topic Words Count"
    }
  }
});
</script>

<script>
var xValues = <%= raw @pie_chart_x %>;
var yValues = <%= raw @pie_chart_y %>;
const length = <%= raw(@pie_chart_x.size) %>;
var barColors = [];
for(var i = 0; i < length; i ++) {
  barColors.push('#' + (0x1000000 + Math.random() * 0xffffff).toString(16).substr(1, 6));
}

new Chart("piechart", {
  type: "pie",
  data: {
    labels: xValues,
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    title: {
      display: true,
      text: "Topic Words Count"
    }
  }
});
</script>

app/views/home/negative_feedbacks.html.erb
<div id="content-wrapper" class="d-flex flex-column mt-4">
    <div class="content-body">
        <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                  <div class="card">
                      <div class="card-body">
                          <h4 class="card-title">Negative Feedbacks</h4>
                          <div class="table-responsive">
                              <table class="table header-border table-hover verticle-middle">
                                  <thead>
                                      <tr>
                                          <th scope="col" style='width: 60%;'>Feedback</th>
                                          <th scope="col">Negativeness</th>
                                          <th scope="col">Negativeness Score</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      <% @feed_backs.each do |feed_back| %>
                                        <% value = (feed_back['scores']['neg'] * 100).to_i %>
                                        <tr>
                                            <td><%= feed_back['feedback'] %></td>
                                            <td>
                                                <div class="progress" style="height: 10px;">
                                                    <div class="progress-bar gradient-1" style="width: <%= value %>%;" role="progressbar"><span class="sr-only"><%= value %></span>
                                                    </div>
                                                </div>
                                            </td>
                                              <td><span class="label gradient-1 btn-rounded"><%= value%></span>
                                            </td>
                                        </tr>
                                      <% end %>
                                  </tbody>
                              </table>
                          </div>
                      </div>
                  </div>
              </div>
            </div>
        </div>
        <!-- #/ container -->
    </div>
</div>

app/views/home/positive_feedbacks.html.erb
<div id="content-wrapper" class="d-flex flex-column mt-4">
    <div class="content-body">
        <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                  <div class="card">
                      <div class="card-body">
                          <h4 class="card-title">Positive Feedbacks</h4>
                          <div class="table-responsive">
                              <table class="table header-border table-hover verticle-middle">
                                  <thead>
                                      <tr>
                                          <th scope="col" style='width: 60%;'>Feedback</th>
                                          <th scope="col">Positiveness</th>
                                          <th scope="col">Positiveness Score</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      <% @feed_backs.each do |feed_back| %>
                                        <% value = (feed_back['scores']['pos'] * 100).to_i %>
                                        <tr>
                                            <td><%= feed_back['feedback'] %></td>
                                            <td>
                                                <div class="progress" style="height: 10px;">
                                                    <div class="progress-bar gradient-1" style="width: <%= value %>%;" role="progressbar"><span class="sr-only"><%= value %></span>
                                                    </div>
                                                </div>
                                            </td>
                                              <td><span class="label gradient-1 btn-rounded"><%= value%></span>
                                            </td>
                                        </tr>
                                      <% end %>
                                  </tbody>
                              </table>
                          </div>
                      </div>
                  </div>
              </div>
            </div>
        </div>
        <!-- #/ container -->
    </div>
</div>

app/views/home/topic_details.html.erb
<div id="content-wrapper" class="d-flex flex-column mt-4">
    <div class="content-body">
        <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                  <div class="card">
                      <div class="card-body">
                          <h4 class="card-title">Topic Details(Corresponding Feedbacks that has word <strong>'<%= params[:word]%>'</strong>)</h4>
                          <div class="table-responsive">
                              <table class="table header-border table-hover verticle-middle">
                                  <thead>
                                      <tr>
                                          <th scope="col" style='width: 60%;'>Feedback</th>
                                          <th scope="col">Score</th>
                                          <th scope="col">Thumbs up count</th>
                                          <th>Postive/Negative</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      <% @feed_backs.each do |feed_back| %>
                                        <tr>
                                            <td><%= feed_back['feedback'] %></td>
                                            <td><%= feed_back['score'] %></td>
                                            <td><%= feed_back['thumbs_up_count'] %></td>
                                            <td>
                                                <% if feed_back['type'] == 'negative' %>
                                                    <button class='btn btn-danger'>Negative feedback</button>
                                                <% elsif feed_back['type'] == 'positive' %>
                                                    <button class='btn btn-success'>Positive Feedback</button>
                                                <% elsif feed_back['type'] == 'neutral' %>
                                                    <button class='btn btn-primary'>Neutral Feedback</button>  
                                                <% end %>
                                            </td>
                                        </tr>
                                      <% end %>
                                  </tbody>
                              </table>
                          </div>
                      </div>
                  </div>
              </div>
            </div>
        </div>
        <!-- #/ container -->
    </div>
</div>

app/views/home/topics.html.erb
<!-- Custom styles for this page -->
<link href="/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
<div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content">
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

                <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-search fa-fw"></i>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                        aria-labelledby="searchDropdown">
                        <form class="form-inline mr-auto w-100 navbar-search">
                            <div class="input-group">
                                <input type="text" class="form-control bg-light border-0 small"
                                    placeholder="Search for..." aria-label="Search"
                                    aria-describedby="basic-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="button">
                                        <i class="fas fa-search fa-sm"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>
            </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- Page Heading -->
            <h1 class="h3 mb-2 text-gray-800">Topics</h1>

            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <tbody>
                              <% @topics.each_with_index do |words, i| %>
                                <tr>
                                    <td>
                                      Topic <%= i + 1 %>:
                                      <% word_array = words.split(', ') %>
                                      <% if word_array.present? %>
                                        <% word_array.each do |word| %>
                                          <%= link_to word, home_topic_details_path(word: word), class: 'btn btn-primary' %>
                                        <% end %>
                                      <% end %>
                                    </td>
                                </tr>
                              <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Copyright &copy; Your Website 2020</span>
            </div>
        </div>
    </footer>
    <!-- End of Footer -->

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>NanogiantNlp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Custom fonts for this template-->
    <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="/css/sb-admin-2.min.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body id="page-top">
      <!-- Page Wrapper -->
      <div id="wrapper">
          <!-- Sidebar -->
          <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

              <!-- Sidebar - Brand -->
              <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                  <!-- <div class="sidebar-brand-icon rotate-n-15">
                      <i class="fas fa-laugh-wink"></i>
                  </div> -->
                  <div class="sidebar-brand-text mx-3">NanoGiant<br/>Ashura Team</div>
              </a>

              <!-- Divider -->
              <hr class="sidebar-divider my-0">

              <!-- Divider -->
              <hr class="sidebar-divider">

              <!-- Heading -->
              <div class="sidebar-heading">
                  Sections
              </div>

              <!-- Nav Item - Tables -->
              <li class="nav-item">
                <%= link_to home_positive_feedbacks_path, class: 'nav-link' do %>
                  <i class="fas fa-fw fa-table"></i>
                  <span>Positive Feedbacks</span>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to home_negative_feedbacks_path, class: 'nav-link' do %>
                  <i class="fas fa-fw fa-table"></i>
                  <span>Negative Feedbacks</span>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to home_topics_path, class: 'nav-link' do %>
                  <i class="fas fa-fw fa-table"></i>
                  <span>Topics</span>
                <% end %>
              </li>

              <!-- Nav Item - Charts -->
              <li class="nav-item">
                <%= link_to home_charts_path, class: 'nav-link' do %>
                  <i class="fas fa-fw fa-chart-area"></i>
                  <span>Charts</span>
                <% end %>
              </li>
          </ul>
          <!-- End of Sidebar -->

          <!-- Content Wrapper -->
          <%= yield %>
          <!-- End of Content Wrapper -->

      </div>
      <!-- End of Page Wrapper -->

      <!-- Scroll to Top Button-->
      <a class="scroll-to-top rounded" href="#page-top">
          <i class="fas fa-angle-up"></i>
      </a>

      <!-- Logout Modal-->
      <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
          aria-hidden="true">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                      <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">×</span>
                      </button>
                  </div>
                  <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                  <div class="modal-footer">
                      <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                      <a class="btn btn-primary" href="login.html">Logout</a>
                  </div>
              </div>
          </div>
      </div>

      <!-- Bootstrap core JavaScript-->
      <script src="/vendor/jquery/jquery.min.js"></script>
      <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

      <!-- Core plugin JavaScript-->
      <script src="/vendor/jquery-easing/jquery.easing.min.js"></script>

      <!-- Custom scripts for all pages-->
      <script src="/js/sb-admin-2.min.js"></script>

  </body>

</html>